version: '3.8'
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ${PWD}/frontend:/app
  backend:
    build:
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - ${PWD}/backend:/app

